const sermons = [
  { id: 'eph', title: '서로 복종하라', passage: '에베소서 5:21-33', date: '2026. 6. 21', type: '주일 오전', summary: '그리스도께 복종하는 교회와 가정의 사랑을 살핍니다.' },
  { id: 'mark', title: '사랑은 선택이 아니라 필수이다', passage: '마가복음 14:63-65', date: '2026. 3. 1', type: '주일 오전', summary: '그리스도를 향한 사랑과 신앙의 결단을 전합니다.' },
  { id: 'gen', title: '서로를 세워주는 부부', passage: '창세기 2:18-25', date: '2026. 5. 17', type: '가정의 달', summary: '창조의 선물인 돕는 배필과 언약의 의미를 나눕니다.' },
  { id: 'john', title: '말씀이 육신이 되어', passage: '요한복음 1:1-14', date: '2025. 12. 25', type: '성탄 예배', summary: '성육신하신 그리스도의 은혜와 영광을 묵상합니다.' }
];

const sermonStoreKey = 'mss-sermons-v1';
const savedSermons = JSON.parse(localStorage.getItem(sermonStoreKey) || 'null');
if (Array.isArray(savedSermons) && savedSermons.length) sermons.splice(0, sermons.length, ...savedSermons);
function persistSermons() { localStorage.setItem(sermonStoreKey, JSON.stringify(sermons)); }
function makeId() { return `sermon-${Date.now().toString(36)}`; }

const state = { route: 'home', sermon: sermons[0], readerSize: 19, dark: localStorage.getItem('mss-theme') === 'dark' };
const notesKey = id => `mss-note-${id}`;
const app = document.querySelector('#app');

function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#039;', '"':'&quot;' }[c])); }
function setTheme() { document.body.classList.toggle('dark', state.dark); localStorage.setItem('mss-theme', state.dark ? 'dark' : 'light'); }
function sermonRow(sermon) { return `<button class="row" data-open="${sermon.id}"><span class="row-icon">▤</span><span class="row-main"><span class="row-title">${sermon.title}</span><span class="row-meta">${sermon.passage} · ${sermon.date}</span></span><span class="chevron">›</span></button>`; }

function home() {
  return `<section class="screen"><span class="eyebrow">주일 · 2026년 6월 21일</span><h1>평안한 주일입니다, 이창륜 목사님.</h1><p class="lead">오늘 강단에 오를 말씀을 마지막으로 살펴보세요.</p>
  <section class="section today-card"><span class="date">오늘의 설교 · ${state.sermon.type}</span><h2>${state.sermon.title}</h2><p>${state.sermon.passage}</p><div class="today-actions"><button class="primary" data-open="${state.sermon.id}">원고 열기</button><button class="secondary" data-route="preach">강단 모드</button></div></section>
  <section class="section"><div class="section-head"><h2>설교 현황</h2><button class="link-button" data-route="sermons">전체 보기</button></div><div class="cards two"><div class="card"><div class="stat-label">올해 설교</div><div class="stat-value">23</div></div><div class="card"><div class="stat-label">준비 중</div><div class="stat-value">3</div></div><div class="card"><div class="stat-label">연속 시리즈</div><div class="stat-value">2</div></div><div class="card"><div class="stat-label">이번 주 메모</div><div class="stat-value">7</div></div></div></section>
  <section class="section"><div class="section-head"><h2>최근 원고</h2></div><div class="list two-column">${sermons.slice(1).map(sermonRow).join('')}</div></section></section>`;
}

function sermonsScreen() {
  return `<section class="screen"><span class="eyebrow">설교 아카이브</span><h1>설교 원고</h1><p class="lead">본문과 주제로 언제든 지난 말씀을 찾습니다.</p><section class="section"><input class="search" id="sermon-search" placeholder="제목, 본문, 키워드 검색" autocomplete="off" /></section><section class="section"><div class="section-head"><h2>전체 ${sermons.length}편</h2><button class="plain-button" id="new-sermon">＋ 새 원고</button></div><div class="list" id="sermon-list">${sermons.map(sermonRow).join('')}</div></section></section>`;
}

function reader() {
  const s = state.sermon;
  const saved = localStorage.getItem(notesKey(s.id)) || '';
  const body = s.body || `<p><span class="verse">“그리스도를 경외함으로 피차 복종하라.”</span></p><p>바울은 그리스도인의 관계를 권리의 언어가 아니라 복음의 언어로 설명합니다. 서로 복종하라는 말씀은 어느 한쪽의 희생만을 요구하지 않습니다. 먼저 자신을 내어주신 그리스도를 바라보며, 사랑으로 섬기는 새로운 공동체의 삶을 부릅니다.</p><p>가정과 교회 안에서 우리는 종종 상대를 바꾸려 애씁니다. 그러나 복음은 먼저 나 자신이 그리스도께 복종하도록 이끕니다. 그 은혜가 마음을 붙들 때, 사랑은 요구가 아니라 기쁨의 섬김으로 피어납니다.</p><p>오늘 우리는 <span class="verse">그리스도께서 교회를 사랑하신 방식</span>을 바라봅니다. 그 사랑을 받은 자답게, 가장 가까운 자리에서부터 서로를 귀히 여기고 세워 갑시다.</p>`;
  return `<section class="screen"><div class="reader-header"><button class="back" data-route="sermons" aria-label="설교 목록으로">‹</button><div class="reader-title"><span class="eyebrow">${s.passage}</span><h1>${s.title}</h1></div><button class="plain-button" data-edit="${s.id}">편집</button><div class="reader-controls"><button id="font-down" aria-label="글자 줄이기">A−</button><button id="font-up" aria-label="글자 키우기">A+</button></div></div><div class="reader-layout"><article class="sermon-paper" style="--reader-size:${state.readerSize}px"><h2>${s.title}</h2>${body}</article><aside><div class="section"><div class="section-head"><h2>강단 메모</h2><span class="save-status" id="save-status">자동 저장</span></div><textarea class="note-box" id="note" placeholder="강단에서 기억할 내용을 적어 두세요.">${escapeHtml(saved)}</textarea></div><div class="section"><button class="plain-button" style="width:100%" data-route="preach">▶ 강단 모드로 열기</button></div></aside></div></section>`;
}

function editor() {
  const s = state.editingId ? sermons.find(item => item.id === state.editingId) : { title:'', passage:'', date: new Date().toLocaleDateString('ko-KR'), type:'주일 오전', summary:'', body:'' };
  return `<section class="screen"><div class="reader-header"><button class="back" data-route="sermons" aria-label="목록으로">‹</button><div class="reader-title"><span class="eyebrow">iPad 원고 편집</span><h1>${state.editingId ? '원고 편집' : '새 원고'}</h1></div></div><form class="editor-form" id="editor-form"><label>설교 제목<input name="title" required value="${escapeHtml(s.title)}" placeholder="예: 서로 복종하라" /></label><div class="form-grid"><label>성경 본문<input name="passage" required value="${escapeHtml(s.passage)}" placeholder="예: 에베소서 5:21-33" /></label><label>예배/유형<input name="type" value="${escapeHtml(s.type)}" /></label></div><label>한 줄 요약<textarea name="summary" rows="2" placeholder="이번 설교의 핵심 메시지">${escapeHtml(s.summary)}</textarea></label><label>원고 본문 <span class="field-help">문단은 빈 줄로 구분됩니다.</span><textarea class="editor-body" name="body" required placeholder="설교 원고를 작성하세요.">${escapeHtml((s.body || '').replace(/<[^>]+>/g, '').replace(/&[^;]+;/g, ''))}</textarea></label><div class="editor-actions"><button type="button" class="plain-button" data-route="sermons">취소</button><button type="submit" class="save-button">기기에 저장</button></div></form></section>`;
}

function syncScreen() { return `<section class="screen"><span class="eyebrow">동기화 · 백업</span><h1>설교 데이터를 지키세요</h1><p class="lead">현재 원고와 강단 메모는 이 기기에 저장됩니다. 기기 간 자동 동기화는 계정 서버를 연결하는 다음 단계입니다.</p><section class="section cards two"><div class="card"><div class="stat-label">현재 저장 원고</div><div class="stat-value">${sermons.length}</div><p class="muted">이 iPhone/iPad의 로컬 데이터</p></div><div class="card"><div class="stat-label">자동 동기화</div><div class="stat-value">대기</div><p class="muted">계정 연결 후 활성화됩니다.</p></div></section><section class="section"><div class="section-head"><h2>지금 할 수 있는 백업</h2></div><div class="list"><button class="row" id="export-data"><span class="row-icon">↓</span><span class="row-main"><span class="row-title">설교 데이터 내보내기</span><span class="row-meta">다른 기기로 옮기거나 보관할 JSON 파일</span></span><span class="chevron">›</span></button><label class="row import-row"><span class="row-icon">↑</span><span class="row-main"><span class="row-title">설교 데이터 가져오기</span><span class="row-meta">백업 파일을 이 기기에 복원</span></span><span class="chevron">›</span><input id="import-data" type="file" accept="application/json" hidden /></label></div></section><section class="section card"><strong>자동 동기화 준비됨</strong><p class="muted">다음 단계에서 계정 로그인, 암호화된 변경 기록, Windows 앱 연결을 붙입니다. 같은 원고를 동시에 고친 경우에는 두 버전을 비교해 선택하도록 설계합니다.</p></section></section>`; }

function schedule() { return `<section class="screen"><span class="eyebrow">사역 일정</span><h1>이번 주</h1><p class="lead">설교와 사역 준비의 리듬을 한 화면에서 확인합니다.</p><section class="section list"><div class="row"><span class="row-icon">☼</span><span class="row-main"><span class="agenda-date">6월 21일 · 주일</span><span class="agenda-title">주일 오전예배 · 서로 복종하라</span><span class="row-meta">에베소서 5:21-33 · 오전 11:00</span></span></div><div class="row"><span class="row-icon">♧</span><span class="row-main"><span class="agenda-date">6월 24일 · 수요일</span><span class="agenda-title">목장 인도자 나눔지 발송</span><span class="row-meta">주간 사역 자료 확인</span></span></div><div class="row"><span class="row-icon">◌</span><span class="row-main"><span class="agenda-date">6월 27일 · 토요일</span><span class="agenda-title">다음 주 설교 본문 연구</span><span class="row-meta">마가복음 15장</span></span></div></section></section>`; }

function notes() { const all = sermons.map(s => ({ sermon:s, value:localStorage.getItem(notesKey(s.id)) || ''})).filter(x => x.value.trim()); return `<section class="screen"><span class="eyebrow">개인 메모</span><h1>강단 메모</h1><p class="lead">원고마다 적어 둔 메모는 이 기기에 안전하게 보관됩니다.</p><section class="section"><div class="list">${all.length ? all.map(({sermon, value}) => `<button class="row" data-open="${sermon.id}"><span class="row-icon">✎</span><span class="row-main"><span class="row-title">${sermon.title}</span><span class="row-meta">${escapeHtml(value.slice(0, 58))}</span></span><span class="chevron">›</span></button>`).join('') : '<div class="card"><strong>아직 메모가 없습니다.</strong><p class="muted">설교 원고에서 강단 메모를 남겨 보세요.</p></div>'}</div></section></section>`; }

function preach() { return `<section class="preach-screen"><div class="preach-top"><button data-open="${state.sermon.id}">← 원고</button><span class="timer" id="timer">00:00</span><button id="preach-font">가</button></div><article class="preach-content"><div class="ref">${state.sermon.passage}</div><p><mark>그리스도를 경외함으로</mark> 피차 복종하라.</p><p>복음은 먼저 자신을 내어주신 그리스도를 바라보게 합니다. 그 은혜가 마음을 붙들 때, 사랑은 요구가 아니라 기쁨의 섬김으로 피어납니다.</p><p>가장 가까운 자리에서부터 서로를 귀히 여기고 세워 갑시다.</p></article></section>`; }

function render() { const screens = {home, sermons:sermonsScreen, reader, editor, schedule, notes, sync:syncScreen, preach}; app.innerHTML = screens[state.route](); document.querySelectorAll('[data-nav]').forEach(b => b.classList.toggle('active', b.dataset.nav === state.route || (state.route === 'reader' && b.dataset.nav === 'sermons'))); bindScreen(); }
function openSermon(id) { state.sermon = sermons.find(s => s.id === id) || sermons[0]; state.route = 'reader'; render(); window.scrollTo(0,0); }

function bindScreen() {
  document.querySelectorAll('[data-route]').forEach(b => b.addEventListener('click', () => { state.route = b.dataset.route; render(); window.scrollTo(0,0); }));
  document.querySelectorAll('[data-nav]').forEach(b => b.addEventListener('click', () => { state.route = b.dataset.nav; render(); window.scrollTo(0,0); }));
  document.querySelectorAll('[data-open]').forEach(b => b.addEventListener('click', () => openSermon(b.dataset.open)));
  document.querySelectorAll('[data-edit]').forEach(b => b.addEventListener('click', () => { state.editingId = b.dataset.edit; state.route = 'editor'; render(); }));
  const search = document.querySelector('#sermon-search'); if (search) search.addEventListener('input', e => { const q = e.target.value.toLowerCase(); document.querySelector('#sermon-list').innerHTML = sermons.filter(s => `${s.title} ${s.passage} ${s.type}`.toLowerCase().includes(q)).map(sermonRow).join('') || '<div class="card">찾는 설교가 없습니다.</div>'; document.querySelectorAll('[data-open]').forEach(b => b.addEventListener('click', () => openSermon(b.dataset.open))); });
  const note = document.querySelector('#note'); if (note) note.addEventListener('input', e => { localStorage.setItem(notesKey(state.sermon.id), e.target.value); const status = document.querySelector('#save-status'); status.textContent = '방금 저장됨'; clearTimeout(window.noteTimer); window.noteTimer = setTimeout(() => status.textContent = '자동 저장', 1400); });
  document.querySelector('#font-up')?.addEventListener('click', () => { state.readerSize = Math.min(28, state.readerSize + 1); render(); });
  document.querySelector('#font-down')?.addEventListener('click', () => { state.readerSize = Math.max(15, state.readerSize - 1); render(); });
  document.querySelector('#new-sermon')?.addEventListener('click', () => { state.editingId = null; state.route = 'editor'; render(); });
  document.querySelector('#editor-form')?.addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.currentTarget); const existing = state.editingId ? sermons.find(item => item.id === state.editingId) : null; const sermon = { id: existing?.id || makeId(), title: form.get('title').trim(), passage: form.get('passage').trim(), type: form.get('type').trim() || '주일 오전', summary: form.get('summary').trim(), date: existing?.date || new Date().toLocaleDateString('ko-KR'), body: form.get('body').trim().split(/\n\s*\n/).filter(Boolean).map(p => `<p>${escapeHtml(p).replace(/\n/g, '<br>')}</p>`).join(''), updatedAt: new Date().toISOString(), version: (existing?.version || 0) + 1 }; if (existing) Object.assign(existing, sermon); else sermons.unshift(sermon); persistSermons(); state.sermon = sermon; state.route = 'reader'; render(); });
  document.querySelector('#export-data')?.addEventListener('click', () => { const data = { schema:'mss-mobile-v1', exportedAt:new Date().toISOString(), sermons, notes:Object.fromEntries(sermons.map(s => [s.id, localStorage.getItem(notesKey(s.id)) || ''])) }; const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], {type:'application/json'})); const link = document.createElement('a'); link.href = url; link.download = `말씀노트-백업-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(url); });
  document.querySelector('#import-data')?.addEventListener('change', async event => { const file = event.target.files[0]; if (!file) return; try { const data = JSON.parse(await file.text()); if (!Array.isArray(data.sermons)) throw new Error(); sermons.splice(0, sermons.length, ...data.sermons); persistSermons(); Object.entries(data.notes || {}).forEach(([id, value]) => localStorage.setItem(notesKey(id), value)); state.sermon = sermons[0]; alert(`${sermons.length}편의 설교를 복원했습니다.`); render(); } catch { alert('말씀노트 백업 파일을 읽지 못했습니다.'); } });
  const timer = document.querySelector('#timer'); if (timer) { const start = Date.now(); window.timerInterval && clearInterval(window.timerInterval); window.timerInterval = setInterval(() => { const seconds = Math.floor((Date.now()-start)/1000); timer.textContent = `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`; }, 1000); } else if (window.timerInterval) { clearInterval(window.timerInterval); window.timerInterval = null; }
}
document.querySelector('#theme-toggle').addEventListener('click', () => { state.dark = !state.dark; setTheme(); });
document.querySelector('#sync-open').addEventListener('click', () => { state.route = 'sync'; render(); });
setTheme(); render();